version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    restart: always
